/**
 * Junk detection: files that are auto-collapsed to a one-line placeholder
 * (lockfiles, build output, minified bundles, generated code) and files that
 * can never be included (binary, secrets, too large).
 *
 * Pure functions only — no DOM, no state — so this module is unit-testable.
 */

export type JunkKind =
  | "lockfile"
  | "build-output"
  | "minified"
  | "generated"
  | "binary"
  | "secrets"
  | "too-large";

export const JUNK_LABEL: Record<JunkKind, string> = {
  lockfile: "lockfile",
  "build-output": "build output",
  minified: "minified",
  generated: "generated code",
  binary: "binary",
  secrets: "secrets",
  "too-large": "too large",
};

/** Junk kinds whose content was read and can be expanded back in by the user. */
export const EXPANDABLE_JUNK: ReadonlySet<JunkKind> = new Set<JunkKind>([
  "lockfile",
  "build-output",
  "minified",
  "generated",
]);

/**
 * Directories that are never read or listed per-file. They are recorded as a
 * single "not scanned" entry instead (package managers, VCS data, caches).
 */
export const NEVER_SCAN_DIRS: ReadonlySet<string> = new Set([
  "node_modules",
  ".git",
  ".svn",
  ".hg",
  ".venv",
  "venv",
  "env",
  "__pycache__",
  ".pytest_cache",
  ".mypy_cache",
  ".cache",
  ".parcel-cache",
  ".turbo",
  ".gradle",
  ".dart_tool",
  "Pods",
  ".terraform",
  "vendor",
  ".idea",
  ".vscode",
  ".next",
  ".nuxt",
  ".output",
  "target",
]);

/** Files that are never listed at all (OS noise). */
export const NEVER_LIST_FILES: ReadonlySet<string> = new Set([".DS_Store", "Thumbs.db", "desktop.ini"]);

/** Build output directories: listed, read, but collapsed by default. (Generated-code dirs are matched by GENERATED_PATH_PATTERNS.) */
export const BUILD_OUTPUT_DIRS: ReadonlySet<string> = new Set(["dist", "build", "out", "coverage"]);

export const LOCKFILES: ReadonlySet<string> = new Set([
  "package-lock.json",
  "npm-shrinkwrap.json",
  "yarn.lock",
  "pnpm-lock.yaml",
  "bun.lockb",
  "bun.lock",
  "cargo.lock",
  "gemfile.lock",
  "poetry.lock",
  "pdm.lock",
  "pipfile.lock",
  "uv.lock",
  "composer.lock",
  "go.sum",
  "packages.lock.json",
  "pubspec.lock",
  "mix.lock",
  "flake.lock",
  "podfile.lock",
  "gradle.lockfile",
]);

const GENERATED_PATH_PATTERNS: RegExp[] = [
  /\.pb\.(go|ts|js|cc|h|py|rs|swift|dart)$/, // protobuf
  /_pb2(_grpc)?\.py$/,
  /_pb\.(js|ts|d\.ts)$/,
  /_grpc(_web)?_pb\.(js|ts)$/,
  /\.pb\.gw\.go$/,
  /\.generated\.[a-z0-9]+$/,
  /\.gen\.[a-z0-9]+$/,
  /\.g\.dart$/,
  /\.freezed\.dart$/,
  /\.graphql\.(ts|js|tsx)$/, // graphql-codegen output
  /\/gql\/(graphql|gql|fragment-masking)\.ts$/,
  /\/__generated__\//,
  /\/generated\//,
  /\.d\.ts\.map$/,
  /\.swagger\.json$/,
  /openapi\.(json|yaml|yml)$/,
];

const GENERATED_HEADER = /@generated|do not edit|code generated by|automatically generated|auto-?generated|generated by (graphql-codegen|protoc|openapi|swagger|prisma|wire)/i;

const MINIFIED_NAME = /\.min\.(js|mjs|cjs|css)$/;
const CODE_FOR_CONTENT_SNIFF = /\.(ts|tsx|js|jsx|mjs|cjs|go|py|rs|java|kt|swift|dart|cs|cc|h|php|rb)$/;

export interface JunkInput {
  path: string;
  /** null = unreadable (binary / too large / secrets) */
  content: string | null;
  /** Reason the content is null, if known. */
  skippedReason?: string;
}

export function isNeverScanPath(path: string): boolean {
  const parts = path.split("/");
  const name = parts[parts.length - 1];
  if (NEVER_LIST_FILES.has(name)) return true;
  return parts.slice(0, -1).some((d) => NEVER_SCAN_DIRS.has(d));
}

/**
 * Returns the never-scan directory prefix for a path (e.g. "packages/app/node_modules"),
 * or null if the path is scannable. Used to collapse thousands of entries into one marker.
 */
export function neverScanDirOf(path: string): string | null {
  const parts = path.split("/");
  for (let i = 0; i < parts.length - 1; i++) {
    if (NEVER_SCAN_DIRS.has(parts[i])) return parts.slice(0, i + 1).join("/");
  }
  return null;
}

export function isLockfile(path: string): boolean {
  const name = (path.split("/").pop() || "").toLowerCase();
  return LOCKFILES.has(name);
}

export function isSecretsFile(path: string): boolean {
  const name = path.split("/").pop() || "";
  if (name === ".env.example" || name === ".env.sample" || name === ".env.template") return false;
  return name === ".env" || name.startsWith(".env.") || /\.(pem|key)$/.test(name) || name === "id_rsa";
}

export function isInBuildOutputDir(path: string): boolean {
  return path
    .split("/")
    .slice(0, -1)
    .some((d) => BUILD_OUTPUT_DIRS.has(d));
}

export function isMinifiedName(path: string): boolean {
  return MINIFIED_NAME.test(path) || /\.(js|css)\.map$/.test(path);
}

export function isGeneratedPath(path: string): boolean {
  return GENERATED_PATH_PATTERNS.some((re) => re.test(path));
}

/** Content-based minification heuristic: very long average lines in a JS/CSS file. */
export function looksMinified(path: string, content: string): boolean {
  if (!/\.(js|mjs|cjs|css)$/.test(path)) return false;
  if (content.length < 2000) return false;
  const lines = content.split("\n");
  const avg = content.length / Math.max(1, lines.length);
  return lines.length <= 5 || avg > 400;
}

export function looksGenerated(path: string, content: string): boolean {
  if (!CODE_FOR_CONTENT_SNIFF.test(path)) return false;
  return GENERATED_HEADER.test(content.slice(0, 600));
}

/**
 * Decide whether a file is junk and why. Order matters: unreadable reasons win,
 * then lockfiles, build output, minified, generated.
 */
export function detectJunk(file: JunkInput): JunkKind | null {
  const { path, content } = file;
  if (isSecretsFile(path)) return "secrets";
  if (content === null) {
    if (file.skippedReason?.startsWith("too large")) return "too-large";
    return "binary";
  }
  if (isLockfile(path)) return "lockfile";
  if (isInBuildOutputDir(path)) return "build-output";
  if (isMinifiedName(path) || looksMinified(path, content)) return "minified";
  if (isGeneratedPath(path) || looksGenerated(path, content)) return "generated";
  return null;
}

export function countLines(text: string): number {
  if (text.length === 0) return 0;
  let n = 1;
  for (let i = 0; i < text.length; i++) if (text.charCodeAt(i) === 10) n++;
  if (text.endsWith("\n")) n--;
  return n;
}

export function formatInt(n: number): string {
  return n.toLocaleString("en-US");
}

function formatSize(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(2)} MB`;
}

export interface PlaceholderInput {
  path: string;
  lines: number;
  size: number;
  content: string | null;
}

/**
 * One-line placeholder, e.g.
 *   "2,341 lines omitted: package-lock.json (lockfile)"
 *   "12.3 KB omitted: logo.png (binary)"
 */
function omittedAmount(file: PlaceholderInput): string {
  if (file.content !== null && file.lines > 0) return `${formatInt(file.lines)} line${file.lines === 1 ? "" : "s"}`;
  return formatSize(file.size);
}

export function placeholderText(file: PlaceholderInput, reason: string): string {
  return `${omittedAmount(file)} omitted: ${file.path} (${reason})`;
}

/** Short label for the file tree row. */
export function omittedLabel(file: PlaceholderInput, kind: JunkKind): string {
  return `${omittedAmount(file)} omitted · ${JUNK_LABEL[kind]}`;
}

export type Disposition =
  | { kind: "full" }
  | { kind: "placeholder"; reason: string }
  | { kind: "skip" };

export interface DispositionInput {
  included: boolean;
  collapsed: boolean;
  content: string | null;
  junk: JunkKind | null;
}

/**
 * How a file shows up in the output:
 *  - evicted by budget   → placeholder "token budget"
 *  - included & readable & expanded → full content
 *  - included & (collapsed | unreadable) → placeholder with junk reason
 *  - not included → skipped silently (the user filtered it out)
 */
export function dispositionOf(file: DispositionInput, evictedReason?: string | null): Disposition {
  if (!file.included) return { kind: "skip" };
  if (evictedReason) return { kind: "placeholder", reason: evictedReason };
  if (file.content === null) return { kind: "placeholder", reason: JUNK_LABEL[file.junk ?? "binary"] };
  if (file.collapsed) return { kind: "placeholder", reason: JUNK_LABEL[file.junk ?? "build-output"] };
  return { kind: "full" };
}
