import { describe, expect, it } from "vitest";
import {
  countLines,
  detectJunk,
  dispositionOf,
  isNeverScanPath,
  neverScanDirOf,
  placeholderText,
  looksMinified,
  looksGenerated,
} from "../junk";

describe("detectJunk", () => {
  it("flags lockfiles", () => {
    for (const p of ["package-lock.json", "yarn.lock", "pnpm-lock.yaml", "Cargo.lock", "Gemfile.lock", "poetry.lock", "composer.lock", "apps/web/package-lock.json"]) {
      expect(detectJunk({ path: p, content: "{}" }), p).toBe("lockfile");
    }
  });

  it("flags build output directories", () => {
    expect(detectJunk({ path: "dist/index.js", content: "x" })).toBe("build-output");
    expect(detectJunk({ path: "packages/ui/build/main.css", content: "x" })).toBe("build-output");
    expect(detectJunk({ path: "out/index.html", content: "x" })).toBe("build-output");
    expect(detectJunk({ path: "coverage/lcov.info", content: "x" })).toBe("build-output");
  });

  it("flags minified files by name and by content shape", () => {
    expect(detectJunk({ path: "vendor/jquery.min.js", content: "x" })).toBe("minified");
    expect(detectJunk({ path: "public/app.min.css", content: "x" })).toBe("minified");
    expect(detectJunk({ path: "public/app.js.map", content: "x" })).toBe("minified");
    const oneLine = "var a=1;".repeat(600); // 4800 chars, single line
    expect(detectJunk({ path: "public/bundle.js", content: oneLine })).toBe("minified");
    expect(looksMinified("src/app.ts", oneLine)).toBe(false); // only js/css are sniffed
  });

  it("flags generated protobuf/graphql code by path and by header", () => {
    expect(detectJunk({ path: "proto/user.pb.go", content: "package proto" })).toBe("generated");
    expect(detectJunk({ path: "proto/user_pb2.py", content: "x" })).toBe("generated");
    expect(detectJunk({ path: "src/gql/graphql.ts", content: "x" })).toBe("generated");
    expect(detectJunk({ path: "src/__generated__/types.ts", content: "x" })).toBe("generated");
    expect(detectJunk({ path: "src/types.ts", content: "/* eslint-disable */\n// @generated by graphql-codegen\nexport type X = 1;" })).toBe("generated");
    expect(looksGenerated("README.md", "DO NOT EDIT")).toBe(false);
  });

  it("flags unreadable files", () => {
    expect(detectJunk({ path: "logo.png", content: null })).toBe("binary");
    expect(detectJunk({ path: "data.csv", content: null, skippedReason: "too large (>1 MB)" })).toBe("too-large");
    expect(detectJunk({ path: ".env", content: "SECRET=1" })).toBe("secrets");
    expect(detectJunk({ path: ".env.example", content: "SECRET=" })).toBeNull();
  });

  it("leaves normal source alone", () => {
    expect(detectJunk({ path: "src/App.tsx", content: "export default function App() {}" })).toBeNull();
    expect(detectJunk({ path: "package.json", content: "{}" })).toBeNull();
    expect(detectJunk({ path: "src/build/helpers.ts", content: "x" })).toBe("build-output"); // dir rule is literal on purpose
  });
});

describe("never-scan paths", () => {
  it("detects package / vcs / cache dirs anywhere in the path", () => {
    expect(isNeverScanPath("node_modules/react/index.js")).toBe(true);
    expect(isNeverScanPath("packages/app/node_modules/x.js")).toBe(true);
    expect(isNeverScanPath(".git/HEAD")).toBe(true);
    expect(isNeverScanPath(".next/server/app.js")).toBe(true);
    expect(isNeverScanPath("target/debug/app")).toBe(true);
    expect(isNeverScanPath("src/.DS_Store")).toBe(true);
    expect(isNeverScanPath("src/index.ts")).toBe(false);
    expect(isNeverScanPath("dist/index.js")).toBe(false); // collapsed, not skipped
  });

  it("reports the top-most skipped directory", () => {
    expect(neverScanDirOf("packages/app/node_modules/x/y.js")).toBe("packages/app/node_modules");
    expect(neverScanDirOf("node_modules/x.js")).toBe("node_modules");
    expect(neverScanDirOf("src/a.ts")).toBeNull();
  });
});

describe("countLines", () => {
  it("counts lines like an editor", () => {
    expect(countLines("")).toBe(0);
    expect(countLines("a")).toBe(1);
    expect(countLines("a\nb")).toBe(2);
    expect(countLines("a\nb\n")).toBe(2);
  });
});

describe("placeholderText", () => {
  it("formats line counts with thousands separators", () => {
    expect(placeholderText({ path: "package-lock.json", lines: 2341, size: 90000, content: "x" }, "lockfile")).toBe(
      "2,341 lines omitted: package-lock.json (lockfile)"
    );
  });
  it("falls back to size for unreadable files", () => {
    expect(placeholderText({ path: "logo.png", lines: 0, size: 12595, content: null }, "binary")).toBe("12.3 KB omitted: logo.png (binary)");
  });
});

describe("dispositionOf", () => {
  const base = { included: true, collapsed: false, content: "x", junk: null };
  it("includes normal selected files in full", () => {
    expect(dispositionOf(base)).toEqual({ kind: "full" });
  });
  it("skips files the user filtered out", () => {
    expect(dispositionOf({ ...base, included: false })).toEqual({ kind: "skip" });
    expect(dispositionOf({ ...base, included: false, collapsed: true, junk: "lockfile" })).toEqual({ kind: "skip" });
  });
  it("renders collapsed junk and unreadable files as placeholders", () => {
    expect(dispositionOf({ ...base, collapsed: true, junk: "lockfile" })).toEqual({ kind: "placeholder", reason: "lockfile" });
    expect(dispositionOf({ ...base, content: null, junk: "binary" })).toEqual({ kind: "placeholder", reason: "binary" });
  });
  it("expanded junk is included in full", () => {
    expect(dispositionOf({ ...base, collapsed: false, junk: "lockfile" })).toEqual({ kind: "full" });
  });
  it("budget eviction wins over everything else", () => {
    expect(dispositionOf(base, "token budget")).toEqual({ kind: "placeholder", reason: "token budget" });
  });
});
